name: Run Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Shell script static analysis
        run: shellcheck bin/fetch-configlet bin/verify-unity-version bin/check-unitybegin bin/run-tests format.sh

      - name: Check concept exercises formatting
        run: |
          find exercises/concept/ -path '*/test-framework' -prune -o \
            \( -iname '*.h' -o -iname '*.c' \) -print0 |\
            xargs --null clang-format --dry-run --Werror

      - name: Check practice exercises formatting
        run: |
          find exercises/practice/ -path '*/test-framework' -prune -o \
            \( -iname '*.h' -o -iname '*.c' \) -print0 |\
            xargs --null clang-format --dry-run --Werror

      - name: Check Unity version
        run: ./bin/verify-unity-version ./exercises/concept ./exercises/practice

      - name: Check unitybegin()
        run: ./bin/check-unitybegin ./exercises/concept ./exercises/practice

      - name: Check include guards
        run: ./bin/check-include-guards ./exercises/concept ./exercises/practice

      - name: Check links
        uses: lycheeverse/lychee-action@f1da3291e1d03cbe11a413ae9f16b62fec99e6b6
        id: lychee
        with:
          args: --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
